name: Azure Web App Deployment

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install and Build Client
      run: |
        cd client
        npm ci
        CI=false npm run build
        mkdir -p ../server/public
        cp -r build/* ../server/public/

    - name: Install Server Dependencies
      run: |
        cd server
        npm ci --production
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SalesIQ'
        publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}
        package: './server'